### ISSUE TITLE
taken tickets should trigger spawner

### ISSUE THREAD

**Issue by praiskup** [praiskup/resalloc#32]
Even though I have this:

```yaml
aws_x86_64_normal:
    max: 15
    max_starting: 5
    max_prealloc: 2
    tags:
    - copr_builder
    - arch_x86_64
    - arch_x86_64_native
    cmd_new: "/var/lib/resallocserver/resalloc_provision/vm-aws-new --arch=x86_64"
    cmd_delete: "/var/lib/resallocserver/resalloc_provision/vm-aws-delete"
```

And several (5+) tag-matching tickets are taken, only two builders are being started
at the same time.
